apiVersion: apps/v1
kind: Deployment
metadata:
  name: voteapp-api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: voteapp-api
  template:
    metadata:
      labels:
        app: voteapp-api
    spec:
      containers:
        - name: api
          image: {{ .Values.api.image }}
          ports:
            - containerPort: {{ .Values.api.port }}
          envFrom:
            - configMapRef:
                name: voteapp-config
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.api.port }}
            initialDelaySeconds: 5
